---
include:
  - board: blecorne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    shield: nice_view
    artifact-name: blecorne_left

  - board: blecorne_right
    shield: nice_view

  # Options for resetting the boards

  # - board: blecorne_left
  #   shield: settings_reset
  # - board: blecorne_right
  #   shield: settings_reset
